#
# Copyright (C) 2020 Nicholas Smith <nicholas.smith@telcoantennas.com.au>
#
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=ModemManager Signal Graph
LUCI_DEPENDS:=+luci-base

PKG_BUILD_DEPENDS:=modemmanager
PKG_LICENSE:=Apache-2.0

include /home/nick/code/telcos/telcos_luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature

