#!/bin/sh
uci set system.led_wwan=led
uci set system.led_wwan.name='WWAN'
uci set system.led_wwan.sysfs='u4019:green:led2'
uci set system.led_wwan.trigger='netdev'
uci set system.led.wwan.dev='wwan0'
uci set system.led.wwan.default='0'
uci add_list system.led.wwan.mode='tx'
uci add_list system.led.wwan.mode='rx'
uci add_list system.led.wwan.mode='link'

uci commit system
