#!/bin/sh
# Set up for automatic failover from WAN to modile data

uci set mwan3.default_rule.use_policy=balanced

uci set mwan3.wan.reliability=1
uci set mwan3.wan.failure_interval=1
uci set mwan3.wan.recovery_interval=1
uci set mwan3.wan.up=3
uci set mwan3.wan.down=3
uci set mwan3.wan.interval=3
uci set mwan3.wan.size=8

uci set mwan3.wan.flush_conntrack=always

uci set mwan3.mobiledata=interface
uci set mwan3.mobiledata.enabled=1
uci set mwan3.mobiledata.initial_state=online
uci set mwan3.mobiledata.family=ipv4
uci set mwan3.mobiledata.track_method=ping
uci set mwan3.mobiledata.reliability=1
uci set mwan3.mobiledata.count=3
uci set mwan3.mobiledata.check_quality=0
uci set mwan3.mobiledata.timeout=10
uci set mwan3.mobiledata.interval=10

uci add_list mwan3.mobiledata.track_ip=8.8.8.8

uci set mwan3.mobiledata.down=5
uci set mwan3.mobiledata.up=2
uci set mwan3.mobiledata.failure_interval=5
uci set mwan3.mobiledata.recovery_interval=10
uci set mwan3.mobiledata.size=8
uci set mwan3.mobiledata.flush_conntrack=always

uci set mwan3.mobdat_m1_w3=member
uci set mwan3.mobdat_m1_w3.interface=mobiledata
uci set mwan3.mobdat_m1_w3.metric=5
uci set mwan3.mobdat_m1_w3.weight=3

uci add_list mwan3.balanced.use_member=mobdat_m1_w3


uci commit mwan3
