#!/bin/sh

modem="/sys/devices/platform/soc/8af8800.usb3/8a00000.dwc3/xhci-hcd.0.auto/usb1/1-1"
uci set network.mobiledata=interface
uci set network.mobiledata.proto=modemmanager
uci set network.mobiledata.device=$modem
uci set network.mobiledata.lowpower="0"
uci set network.mobiledata.metric=50
uci commit network.mobiledata
unset modem

