#!/bin/sh
uci set wireless.default_radio0.ssid="Telco Bridge AP"
uci set wireless.default_radio0.channel="auto"
uci set wireless.default_radio0.country="AU"
uci set wireless.default_radio0.disabled=0

uci set wireless.radio0.ssid="Telco Bridge AP"
uci set wireless.radio0.channel="auto"
uci set wireless.radio0.country="AU"
uci set wireless.radio0.disabled=0

uci commit wireless
exit 0
