#!/bin/sh
uci set system.@system[0].osstring='TelcOS 1.2 Melaleuca'
uci set system.@system[0].hostname='TelcoElectronicsT1'
uci set system.@system[0].zonename='Australia/Brisbane'
uci set system.@system[0].timezone='AEST-10'
uci set luci.apply.rollback='90'
uci set luci.diag.dns='www.telcoantennas.com.au'
uci set luci.diag.ping='www.telcoantennas.com.au'
uci set luci.diag.route='www.telcoantennas.com.au'
uci set system.ntp.server='0.au.pool.ntp.org'
uci add_list system.ntp.server='1.au.pool.ntp.org'
uci add_list system.ntp.server='2.au.pool.ntp.org'
uci add_list system.ntp.server='3.au.pool.ntp.org'
uci commit system
uci commit luci
