#!/bin/sh
uci set system.led_wlan=led
uci set system.led_wlan.name='WLAN'
uci set system.led_wlan.sysfs='tel-t1:blue:wlan'
uci set system.led_wlan.trigger='netdev'
uci set system.led_wlan.dev='wlan0'
uci set system.led.wlan.default='0'
uci add_list system.led_wlan.mode='link'
uci add_list system.led_wlan.mode='tx'
uci add_list system.led_wlan.mode='rx'

uci set system.led_wwan=led
uci set system.led_wwan.name='WWAN'
uci set system.led_wwan.sysfs='tel-t1:blue:wan'
uci set system.led_wwan.trigger='netdev'
uci set system.led.wwan.dev='wwan0'
uci set system.led.wwan.default='0'
uci add_list system.led.wwan.mode='tx'
uci add_list system.led.wwan.mode='rx'
uci add_list system.led.wwan.mode='link'

uci commit system
