#!/bin/sh
uci set wireless.@wifi-device[0].ssid="Telco T1 2.4GHz"
uci set wireless.default_radio0.ssid="Telco T1 2.4GHz"
uci set wireless.@wifi-device[0].channel="auto"
uci set wireless.@wifi-device[0].country="AU"
uci set wireless.@wifi-device[0].disabled=0
uci set wireless.default_radio1.ssid="Telco T1 5GHz"
uci set wireless.@wifi-device[1].ssid="Telco T1 5GHz"
uci set wireless.@wifi-device[1].channel="auto"
uci set wireless.@wifi-device[1].country="AU"
uci set wireless.@wifi-device[1].disabled=0
uci commit wireless
exit 0
