#!/bin/sh
uci set wireless.default_radio0.ssid="Telco X1 2.4GHz"
uci set wireless.default_radio0.channel="auto"
uci set wireless.default_radio0.country="AU"
uci set wireless.default_radio0.disabled=0
uci set wireless.default_radio1.ssid="Telco X1 5GHz"
uci set wireless.default_radio1.channel="auto"
uci set wireless.default_radio1.country="AU"
uci set wireless.default_radio1.disabled=0
uci commit wireless
exit 0
